name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: windows-latest
    steps:
      - name: Output GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
